#!/bin/bash

#the real purpose of -d is because fslcpgeom will actually changes the number of maps in a file
#in wb_command, the option actually disables the spatial dimension check, but it probably also does that in fsl, too (in addition to "don't do the stupid thing")
ignoredims=()

#accept -d anywhere, any number of times, just because
while [[ "$1" == "-d" ]]
do
    ignoredims=(-ignore-dims)
    shift
done

#fsl and its magic extensions...
ref=$(imglob -extensions "$1")
shift

while [[ "$1" == "-d" ]]
do
    ignoredims=(-ignore-dims)
    shift
done

target=$(imglob -extensions "$1")
shift

while [[ "$1" == "-d" ]]
do
    ignoredims=(-ignore-dims)
    shift
done

#wb_command -volume-set-space "$target" "$target" -file "$ref" "${ignoredims[@]}"
wb_command -volume-set-space "$target" "$target" -file "$ref"

